version: "3.6"

services:
 test:
  build:
   context: ./.test
   args:
    ENGINE_IMAGE: ${ENGINE_IMAGE:-ghcr.io/minetest-hosting/minetest-docker:5.8.0}
    MTG_VERSION: ${MTG_VERSION:-5.8.0}
  entrypoint: "minetestserver --config /minetest.conf --gameid minetest"
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/technic/"
    - "./.test/minetest.conf:/minetest.conf"
    - "./.test/registered_nodes.txt:/root/.minetest/worlds/world/registered_nodes.txt"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}