name: mineunit

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: mineunit
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./technic
        badge-label: Test coverage

    - uses: RubbaBoy/BYOB@v1.2.0
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        NAME: "${{ steps.mineunit.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: mineunit-cnc
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./technic_cnc
        badge-name: coverage-cnc
        badge-label: Test coverage

    - uses: RubbaBoy/BYOB@v1.2.0
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        NAME: "${{ steps.mineunit-cnc.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit-cnc.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit-cnc.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit-cnc.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: mineunit-chests
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./technic_chests
        badge-name: coverage-chests
        badge-label: Test coverage

    - uses: KeisukeYamashita/create-comment@v1
      if: success() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Click for detailed source code test coverage report</i></summary>
          
          ### Test coverage report for Technic CNC ${{ steps.mineunit-cnc.outputs.coverage-total }} in ${{ steps.mineunit-cnc.outputs.coverage-files }} files:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-cnc.outputs.mineunit-report }}
          ```
          
          ### Test coverage report for technic chests ${{ steps.mineunit-chests.outputs.coverage-total }} in ${{ steps.mineunit-chests.outputs.coverage-files }} files:
          ```
          File          Hits Missed Coverage
          ----------------------------------
          ${{ steps.mineunit-chests.outputs.mineunit-report }}
          ```
          
          ### Test coverage report for technic ${{ steps.mineunit.outputs.coverage-total }} in ${{ steps.mineunit.outputs.coverage-files }} files:
          ```
          File                                      Hits Missed Coverage
          --------------------------------------------------------------
          ${{ steps.mineunit.outputs.mineunit-report }}
          ```
          
          ### Raw test runner output for geeks:
          CNC:
          ```
          ${{ steps.mineunit-cnc.outputs.mineunit-stdout }}
          ```
          Chests:
          ```
          ${{ steps.mineunit-chests.outputs.mineunit-stdout }}
          ```
          Technic:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>

    - uses: KeisukeYamashita/create-comment@v1
      if: failure() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Mineunit failed regression tests, click for details</i></summary>
          
          ### Regression test log for Technic CNC:
          ```
          ${{ steps.mineunit-cnc.outputs.mineunit-stdout }}
          ```
          
          ### Regression test log for Technic Chests:
          ```
          ${{ steps.mineunit-chests.outputs.mineunit-stdout }}
          ```
          
          ### Regression test log for Technic:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>
